version: '3.9'

services:
  app:
    image: 'ruby'
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    ports:
      - "3000:3000"
    command: "bundle && ruby server.rb"

volumes:
  rubygems:
  gemconfig:
