#!/bin/bash

docker run \
  --rm \
  --name rebase-labs \
  -w /app \
  -v $(pwd):/app \
  -p 3000:3000 \
  --network rebase-labs \
  ruby \
  bash -c "gem install rack sinatra puma pg && ruby server.rb"